Controllers/PagoController.cs
using Ecommerce_2024_1_NJD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Newtonsoft.Json;
using System.Data;

namespace Ecommerce_2024_1_NJD.Controllers
{
    public class PagoController : Controller
    {
        public readonly IConfiguration _iconfig; //recuperar el ConnectionStrings
        public PagoController(IConfiguration iconfig)
        {
            _iconfig = iconfig;
        }

        // Método para obtener todos los pedidos de la base de datos
        // Método para obtener todos los pedidos de la base de datos
        private IEnumerable<Pedido> GetPedidosFromDatabase(int? id = null)
        {
            List<Pedido> pedidos = new List<Pedido>();

            using (SqlConnection connection = new SqlConnection(_iconfig.GetConnectionString("cadena")))
            {
                //Devolver pedidos incluso si no hay pagos asociados
                SqlCommand command = new SqlCommand("SP_PEDIDOSYPAGOS", connection);
                command.CommandType = CommandType.StoredProcedure;

                // Si id tiene un valor, agregamos el parámetro @Id
                if (id.HasValue)
                {
                    command.Parameters.AddWithValue("@IdPedido", id.Value);
                }

                    connection.Open();
                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        Pedido pedido = new Pedido
                        {
                            idPedido = (int)reader["idPedido"],
                            estadoPedido = reader["Estado"].ToString(),
                            fechaRegistroPedido = (DateTime)reader["FechaRegistroPedido"],
                            idUsuario = (int)reader["id_usuario"],
                            dniCliente = reader["dniC"].ToString(),
                            direccionDestino = reader["direccionDestino"].ToString(),

                            idPago = reader["IdPago"] != DBNull.Value ? (int)reader["IdPago"] : 0,
                            Fecha = reader["Fecha"] != DBNull.Value ? (DateTime)reader["Fecha"] : DateTime.MinValue,
                            MetodoPago = reader["MetodoPago"] != DBNull.Value ? reader["MetodoPago"].ToString() : ""
                        };
                        // Obtener los detalles del pedido usando el procedimiento almacenado ObtenerDetallesPedidoPorId
                        pedido.detallesPedido = ObtenerDetallesPedidoPorId(pedido.idPedido);

                        pedidos.Add(pedido);
                    }
                
            }

            return pedidos;
        }

        public IActionResult RealizarPago(int? id)
        {
            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");
            ViewData["CantidadProdCr"] = RecoverCantidadProd();

            if (id.HasValue)
            {
                //POR MEDIO DE LA URL
                IEnumerable<Pedido> pedidos = GetPedidosFromDatabase(id);
                return View(pedidos);
            }
            else
            {
                //LISTADO NORMAL-PASANDO OBJETO COMO = NULL
                IEnumerable<Pedido> pedidos = GetPedidosFromDatabase();
                return View("RealizarPago", pedidos);
            }
        }


        // Método privado para obtener la cantidad de productos en la canasta
        private int RecoverCantidadProd()
        {
            var canasta = HttpContext.Session.GetString("canasta");
            if (string.IsNullOrEmpty(canasta))
            {
                return 0; // Si el carrito está vacío, retorna 0 productos
            }
            else
            {
                var productosEnCarrito = JsonConvert.DeserializeObject<List<Producto>>(canasta);
                return productosEnCarrito.Sum(p => p.cantidad); // Retorna la cantidad total de productos en el carrito
            }
        }


        [HttpPost]
        public IActionResult RealizarPago(int idPedido, string metodoPago)
        {
            // Obtener el ID del usuario logueado
            string idUsuario = HttpContext.Session.GetString("IdUsuario");

            // Registrar el pago
            int idPago = RegistrarPago(idPedido, metodoPago);

            // Redireccionar a alguna vista de confirmación o a donde sea apropiado
            return RedirectToAction("Portal", "Ecommerce");
        }




        // Método para registrar el pago
        public int RegistrarPago(int idPedido, string metodoPago)
        {
            int idPago = 0;
            string connectionString = _iconfig.GetConnectionString("cadena");

            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                cn.Open();
                string query = "SpRegitrarPago"; // Asegúrate de que el nombre del procedimiento almacenado sea correcto
                SqlCommand cmd = new SqlCommand(query, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@idPedido", idPedido);
                cmd.Parameters.AddWithValue("@metodoPago", metodoPago);

                SqlDataReader dr = cmd.ExecuteReader();

                if (dr.Read())
                {
                    idPago = Convert.ToInt32(dr["IdPago"]);
                }

                cn.Close();
            }

            return idPago;
        }

        public List<Pedido> ObtenerDetallesPedidoPorId(int idPedido)
        {
            List<Pedido> detallesPedidos = new List<Pedido>();

            string connectionString = _iconfig.GetConnectionString("cadena");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string query = "ObtenerDetallesPedidoPorId";
                SqlCommand command = new SqlCommand(query, connection);
                command.CommandType = CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@idPedido", idPedido);

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    Pedido detallePedido = new Pedido
                    {
                        idProducto = Convert.ToInt32(reader["IdProducto"]),
                        NombreProducto = reader["NombreProducto"].ToString(),
                        cantidad = Convert.ToInt32(reader["Cantidad"]),
                        Precio = Convert.ToDecimal(reader["Precio"])
                    };
                    detallesPedidos.Add(detallePedido);
                }
            }

            return detallesPedidos;
        }
    }
}

Controllers/ProductoController.cs
using Ecommerce_2024_1_NJD.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.IdentityModel.Tokens;
using NuGet.Protocol.Plugins;
using System.Data;
using System.Globalization;

namespace Ecommerce_2024_1_NJD.Controllers
{

    public class ProductoController : Controller
    {
        // Instanciar conexión SQL
        public readonly IConfiguration _config;
        public readonly IWebHostEnvironment _hostEnvironment;



        public ProductoController(IConfiguration config, IWebHostEnvironment hostEnvironment)
        {
            _config = config;
            _hostEnvironment = hostEnvironment;
        }
        //GET
        public IActionResult RegistrarProducto()
        {
            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");
            ViewData["Rol"] = HttpContext.Session.GetString("Rol");
            // Obtener la lista de categorías
            //-------------------------------------------------------------------------------------------//
            List<Producto> categorias = ObtenerCategorias();
            SelectList categoriasSelectList = new SelectList(categorias, "IdCategoria", "NombreCategoria");
            //-------------------------------------------------------------------------------------------//
            ViewData["Categorias"] = categoriasSelectList;

            if (HttpContext.Session.GetString("Rol") == "Administrador" || HttpContext.Session.GetString("Rol") == "Moderador")
            {
                return View();
            }
            else if (HttpContext.Session.GetString("Rol") == "Solicitante")
            {
                return RedirectToAction("AprobacionPendiente", "Usuario");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }



        // POST: Registrar un nuevo producto
        [HttpPost]
        public async Task<IActionResult> RegistrarProducto(IFormFile Imagen, Producto model)
        {
            try
            {
                if (Imagen != null && Imagen.Length > 0)
                {
                    //INTECTAR Y GUARDAR IMG EN MEMORIA SERVIDOR
                    var uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "ImagenesProducto");
                    var fileName = Guid.NewGuid().ToString() + "_" + Imagen.FileName;
                    var filePath = Path.Combine(uploadsFolder, fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await Imagen.CopyToAsync(stream);
                    }

                    string connectionString = _config.GetConnectionString("cadena");
                    using (SqlConnection cn = new SqlConnection(connectionString))
                    {
                        cn.Open();
                        using (SqlCommand command = new SqlCommand("Sp_RegistrarProducto", cn))
                        {
                            command.CommandType = CommandType.StoredProcedure;
                            command.Parameters.AddWithValue("@NombreProducto", model.Nombre);
                            command.Parameters.AddWithValue("@IDCategoria", model.IdCategoria);
                            command.Parameters.AddWithValue("@Precio", model.Precio);
                            command.Parameters.AddWithValue("@Stock", model.Stock);
                            command.Parameters.AddWithValue("@Imagen", ConvertImageToByteArray(filePath)); // GUARADNDO IMAGEN COMO ARREGLO (BYTES)
                            var idProducto = command.ExecuteScalar();
                            if (idProducto != null)
                            {
                                ViewBag.Message = "Producto registrado exitosamente con ID: " + idProducto.ToString();
                            }
                            else
                            {
                                ViewBag.Error = "Ocurrió un error al registrar el producto.";
                            }
                        }
                    }
                }
                else
                {
                    // MANEJO CUANDO NO SE SUBE IMAGEN
                    ModelState.AddModelError("Imagen", "Por favor, seleccione una imagen.");
                    return View(model);
                }

                return RedirectToAction("RegistrarProducto");
            }
            catch (Exception ex)
            {
                // MANEJO EX CUANDO HAY ERROE EN EL SQL - SP
                ViewBag.ErrorEx = "Se produjo un error al procesar tu solicitud. Por favor, inténtalo de nuevo más tarde.";

                return View(model);
            }
        }

        public List<Producto> ObtenerCategorias()
        {
            string connectionString = _config.GetConnectionString("cadena");
            List<Producto> categorias = new List<Producto>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string query = "SELECT idCategoria, NombreCategoria FROM Categoria";
                SqlCommand command = new SqlCommand(query, connection);

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                while (reader.Read())
                {
                    Producto categoria = new Producto
                    {
                        IdCategoria = Convert.ToInt32(reader["idCategoria"]),
                        NombreCategoria = reader["NombreCategoria"].ToString()
                    };
                    categorias.Add(categoria);
                }
            }

            return categorias;
        }



        // Método para convertir la imagen a un array de bytes
        private byte[] ConvertImageToByteArray(string imagePath)
        {
            byte[] imageBytes = System.IO.File.ReadAllBytes(imagePath);
            return imageBytes;
        }

        public IActionResult ObtenerImagen(int id)
        {
            string connectionString = _config.GetConnectionString("cadena");
            byte[] imageBytes;

            // Consulta para obtener la imagen del producto según su ID
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                cn.Open();
                using (SqlCommand command = new SqlCommand("Sp_ObtenerImagenProducto", cn))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@IdProducto", id);

                    // Ejecutar el comando para obtener la imagen
                    imageBytes = (byte[])command.ExecuteScalar();
                }
            }
            if (imageBytes != null && imageBytes.Length > 0)
            {
                // Retornar la imagen como un archivo de imagen al navegador
                return File(imageBytes, "image/png"); // Suponiendo que las imágenes son PNG
            }
            else
            {
                // Si los bytes de la imagen son nulos o están vacíos, puedes manejar el error de alguna manera
                return NotFound(); // Por ejemplo, puedes retornar un error 404
            }

        }
        [HttpPost]
        public IActionResult ActualizarProducto(int idProducto, string nombre, IFormFile Imagen, decimal precio, int stock, int idCategoria)
        {
            var model = new Producto
            {
                IdProducto = idProducto,
                Nombre = nombre,
                Imagen = Imagen,
                Precio = precio,
                Stock = stock,
                IdCategoria = idCategoria,
            };

            var success = ActualizarProductoDatos(model);
            return Json(new { success });
        }

        public async Task<bool> ActualizarProductoDatos(Producto model)
        {
            try
            {
                string connectionString = _config.GetConnectionString("cadena");
                using (SqlConnection cn = new SqlConnection(connectionString))
                {
                    cn.Open();
                    using (SqlCommand command = new SqlCommand("SP_ActualizarProducto", cn))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@idProducto", model.IdProducto);

                        if (!string.IsNullOrEmpty(model.Nombre))
                            command.Parameters.AddWithValue("@NombreProducto", model.Nombre);

                        if (model.Imagen != null)
                        {
                            // INTEGRAR Y GUARDAR IMAGEN EN EL SERVIDOR
                            var uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "ImagenesProducto");
                            var fileName = Guid.NewGuid().ToString() + "_" + model.Imagen.FileName;
                            var filePath = Path.Combine(uploadsFolder, fileName);

                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await model.Imagen.CopyToAsync(stream);
                            }

                            // Guardar imagen como arreglo de bytes
                            byte[] imageBytes = ConvertImageToByteArray(filePath);
                            command.Parameters.AddWithValue("@Imagen", imageBytes);
                        }

                        if (model.Precio != null)
                            command.Parameters.AddWithValue("@Precio", model.Precio);

                        if (model.Stock != null)
                            command.Parameters.AddWithValue("@Stock", model.Stock);

                        if (model.IdCategoria != null)

Views/Pedidos/ListadoPedidosxUsuario.cshtml
@model List<Ecommerce_2024_1_NJD.Models.Pedido>

<!--Pa usar el layout-->
@{Layout = "_LayoutTienda";}

<!--Pa complementar el titulo en el Layout-->
@{ViewData["Title"] = "Listado de Pedidos";}



@if (!string.IsNullOrEmpty(ViewData["IdUsuario"]?.ToString()) && !string.IsNullOrEmpty(ViewData["FullName"]?.ToString()))
{
    <style>body{background-color:#EEEEEE}</style>

    <div class="container-table100 text-center">

        <div class="wrap-table100">
            <h1 class="text-start my-0 text-dark fs-2">Historial de pedidos de @ViewData["FullName"]</h1>
            <hr class="my-3">

            <div class="table-100">
                <select id="estadoSelector" class="form-select mb-3 col-6">
                    <option disabled selected value="">- Filtrar pedidos -</option>
                    <option value="0">Mostrar todo</option>
                    <option value="1">Mostrar pedidos pagados</option>
                    <option value="2">Mostrar pedidos pendientes</option>
                </select>
            </div>

            <div class="table100">
                <table id="tabla1" class="table-striped" style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
                    <thead>
                        <tr class="table100-head text-light">
                            <th class="align-middle">ID Pedido</th>
                            <th class="align-middle">Estado</th>
                            <th class="align-middle">Fecha de Registro</th>
                            <th class="align-middle">DNI del Cliente</th>
                            <th class="align-middle">Dirección de Destino</th>
                            <th class="align-middle">Detalles</th> <!-- Nueva columna para el botón Detalles -->
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var pedido in Model)
                        {
                            <tr>
                                <td class="align-middle">@pedido.idPedido</td>
                                <td class="align-middle fw-bold estado">@pedido.estadoPedido</td>
                                <td class="align-middle">@pedido.fechaRegistroPedido.ToShortDateString()</td>
                                <td class="align-middle">@pedido.dniCliente</td>
                                <td class="align-middle">@pedido.direccionDestino</td>
                                <td class="align-middle">
                                    <button type="button" class="btn btn-cyan fw-bold" data-toggle="modal" data-target="#detallesModal-@pedido.idPedido">Ver detalles</button>
                                </td> <!-- Botón Detalles -->
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>




    @foreach (var pedido in Model)
    {
        <!-- Modal para mostrar los detalles del pedido -->
        <div class="modal modal-lg fade " id="detallesModal-@pedido.idPedido" tabindex="-1" role="dialog" aria-labelledby="detallesModalLabel-@pedido.idPedido" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
                <div class="modal-content bg-dark">
                    <div class="modal-header text-light" style="background-color:black; border-color:gray">
                        <h5 class="modal-title fw-bold" id="detallesModalLabel-@pedido.idPedido">Detalles del Pedido #@pedido.idPedido</h5>
                        <button type="button" class="btn-close btn-close-white" data-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body p-0">
                        <table id="tabla2" class="table table-striped table-dark mb-0" style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
                            <thead>
                                <tr class="table100-head text-light text-center">
                                    <th class="align-middle">#</th>
                                    <th class="align-middle">Producto</th>
                                    <th class="align-middle">Cantidad</th>
                                    <th class="align-middle">Total</th>
                                    <th class="align-middle"></th>
                                </tr>
                            </thead>
                            <tbody class="p-0">
                                @foreach (var detalle in pedido.detallesPedido)
                                {
                                    <tr class="text-center py-3" style="border-color:gray">
                                        <td class="align-middle">@detalle.idProducto</td>
                                        <td class="align-middle">@detalle.NombreProducto</td>
                                        <td class="align-middle">@detalle.cantidad</td>
                                        <td class="align-middle">S/ @detalle.Precio</td>
                                        <td class="align-middle">
                                            <img class="rounded" style="width: 100px; height: 100px;" src="@Url.Action("ObtenerImagen", "Producto", new { id = detalle.idProducto })" alt="Imagen del Producto" />
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>

                    <div class="modal-footer d-block" style="background-color:black; border-color:gray">
                        <center>

                            @if (pedido.estadoPedido == "Pendiente")
                            {
                                <a class="btn btn-success fw-bold" asp-controller="Pago" asp-action="RealizarPago" asp-route-id="@pedido.idPedido">Proceder al pago</a>
                            }
                            else
                            {
                                <a class="btn btn-info fw-bold" asp-controller="Pago" asp-action="RealizarPago" asp-route-id="@pedido.idPedido">Más información</a>
                            }

                            
                            <button type="button" class="btn btn-secondary fw-bold" data-dismiss="modal">Cerrar</button>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    }



}
else
{
    <div class="alert alert-danger" role="alert">
        No se pudo obtener el resultado del inicio de sesión.
    </div>
}



<script>
    // Pa cuando cambie el valor del select
    document.getElementById("estadoSelector").addEventListener("change", function () {
        var selectedValue = this.value; // Valor del select
        var rows = document.querySelectorAll('#tabla1 tbody tr'); // Obtener las filas

        // Loop through all table rows
        rows.forEach(function (row) {
            var celdaEstado = row.querySelector('.estado'); // Obtener la celda que contiene el estado
            var estado = celdaEstado.textContent.trim(); // Obtener el valor del estado en la celda
            
            // Cambiar entre la visibilidad de las filas
            if (selectedValue === "0" ||
                (selectedValue === "1" && estado === "Pagado") ||
                (selectedValue === "2" && estado === "Pendiente")) {
                row.style.display = "table-row"; // Mostrar filas
            } else {
                row.style.display = "none"; // Esconder las filas
            }
        });
    });
</script>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    function detallesModal(id) {
        var modal = document.getElementById("myModal_" + id);
        modal.style.display = "block";
    }

    function cerrarModal(id) {
        var modal = document.getElementById("myModal_" + id);
        modal.style.display = "none";
    }
</script>

Views/Pedidos/ListarPedidos.cshtml
@{
    Layout = "_LayoutDashboard";
}


@{
    ViewData["Title"] = "Pedidos";
}

<h3 class="text-center py-3 text-light" style="background-color: rgb(47 47 47);">
    <span class="material-icons-outlined">fact_check</span>&nbsp;Pedidos
</h3>

<div class="w-95 mx-auto">

    @using (Html.BeginForm("BuscarPedidos", "Pedidos", FormMethod.Post))
    {
        <div class="d-flex">
            @if (@ViewBag.StrBusqueda != null && @ViewBag.StrBusqueda != "*")
            {
                <input value="@ViewBag.StrBusqueda" placeholder="Buscar pedidos por nombre o ID de cliente" class="form-control" type="text" name="nombreBusqueda" />
            }
            else
            {
                <input value="" placeholder="Buscar pedidos por nombre o ID de cliente" class="form-control" type="text" name="nombreBusqueda" />
            }
            &nbsp;&nbsp;
            <button class="btn btn-dark" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </div>

    }

    <hr class="text-dark">

    @if (@ViewBag.Pedidos != null && @ViewBag.Pedidos.Count > 0)
    {
        <table class="text-center table table-bordered table-striped table-hover">
            <tr>
                <th style="background-color: rgb(47 47 47); color:white" class="align-middle">#</th>
                <th style="background-color: rgb(47 47 47); color:white" class="align-middle">Cliente</th>
                <th style="background-color: rgb(47 47 47); color:white" class="align-middle">Dirección de entrega</th>
                <th style="background-color: rgb(47 47 47); color:white" class="align-middle">DNI</th>
                <th style="background-color: rgb(47 47 47); color:white" class="align-middle">Fecha de Registro</th>
                <th style="background-color: rgb(47 47 47); color:white" class="align-middle">Acciones</th>
            </tr>

            @foreach (var pedido in ViewBag.Pedidos)
            {
            <tr>
                <td class="align-middle">@pedido.idPedido</td>
                <td class="align-middle">@pedido.Cliente</td>
                <td class="align-middle">@pedido.direccionDestino</td>
                <td class="align-middle">@pedido.dniCliente</td>
                <td class="align-middle">@pedido.fechaRegistroPedido.ToString("dd/MM/yyyy")</td>
                
                <td class="align-middle">
                    <button type="button" class="btn bg-success fw-bold text-light" data-bs-toggle="modal" data-bs-target="#detallesModal-@pedido.idPedido">Detalles</button>
                </td>
                
            </tr>
            }
        </table>
    }
    else
    {
        <p class="text-dark">No se encontraron resultados.</p>
        <a asp-action="ListarPedidos" asp-controller="Pedidos" class="btn btn-dark">Ver todos los pedidos</a>
    }

</div>


@foreach (var pedido in ViewBag.Pedidos)
{
    <!-- Modal para mostrar los detalles del pedido -->
    <div class="modal modal-lg fade " id="detallesModal-@pedido.idPedido" tabindex="-1" role="dialog" aria-labelledby="detallesModalLabel-@pedido.idPedido" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content bg-dark">
                <div class="modal-header text-light" style="background-color:black; border-color:gray">
                    <h5 class="modal-title fw-bold" id="detallesModalLabel-@pedido.idPedido">Detalles del Pedido #@pedido.idPedido</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body p-0">

                    @if(pedido.estadoPedido == "Pagado") {
                        <div class="bg-info text-dark">
                            <p class="w-95 text-center mx-auto my-0 py-3 fw-bold">Este pedido fue pagado el día @pedido.FechaPago.ToString("dd/MM/yyyy").</p>
                        </div>
                        
                    }
                    else
                    {
                        <div class="bg-warning text-dark">
                            <p class="w-95 text-center mx-auto my-0 py-3 fw-bold">Este pedido está actualmente pendiente de pago.</p>
                        </div>

                    }

                    <hr class="my-0 text-light">
                    
                    
                    <table id="tabla2" class="table table-striped table-dark mb-0" style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
                        <thead>
                            <tr class="table100-head text-light text-center">
                                <th style="background-color: rgb(47 47 47);" class="align-middle">#</th>
                                <th style="background-color: rgb(47 47 47);" class="align-middle">Producto</th>
                                <th style="background-color: rgb(47 47 47);" class="align-middle">Cantidad</th>
                                <th style="background-color: rgb(47 47 47);" class="align-middle">Total</th>
                                <th style="background-color: rgb(47 47 47);" class="align-middle"></th>
                            </tr>
                        </thead>
                        <tbody class="p-0">
                            @foreach (var detalle in pedido.detallesPedido)
                            {
                                <tr class="text-center py-3" style="border-color:gray">
                                    <td class="align-middle">@detalle.idProducto</td>
                                    <td class="align-middle">@detalle.NombreProducto</td>
                                    <td class="align-middle">@detalle.cantidad</td>
                                    <td class="align-middle">S/ @detalle.Precio</td>
                                    <td class="align-middle">
                                        <img class="rounded" style="width: 100px; height: 100px;" src="@Url.Action("ObtenerImagen", "Producto", new { id = detalle.idProducto })" alt="Imagen del Producto" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>

                <div class="modal-footer d-block" style="background-color:black; border-color:gray">
                    <button type="button" class="btn btn-secondary fw-bold d-block mx-auto" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
}