Controllers/ECommerceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using System.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Session;
using Ecommerce_2024_1_NJD.Models;
using Microsoft.Win32;
using Humanizer;
using System.Text;
using Microsoft.IdentityModel.Tokens;

namespace Ecommerce_2024_1_NJD.Controllers
{
    public class ECommerceController : Controller
    {
        public readonly IConfiguration _iconfig; //recuperar el ConnectionStrings
        public ECommerceController(IConfiguration iconfig)
        {
            _iconfig = iconfig;
        }

        IEnumerable<Producto> Catalogo()
        {
            List<Producto> temporal = new List<Producto>();
            string connectionString = _iconfig.GetConnectionString("cadena");
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                cn.Open();
                string query = @"SELECT p.IdProducto, p.NombreProducto, p.IdCategoria, c.NombreCategoria AS NombreCategoria, 
                               p.Precio, p.Stock, CONVERT(varchar, p.FechaRegistro, 103) AS FechaRegistro
                               FROM Producto p
                               INNER JOIN Categoria c ON p.IdCategoria = c.IdCategoria Where P.Estado = 'Disponible'";
                SqlCommand cmd = new SqlCommand(query, cn);
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Producto producto = new Producto()
                    {
                        IdProducto = Convert.ToInt32(dr["IdProducto"]),
                        Nombre = dr["NombreProducto"].ToString(),
                        NombreCategoria = dr["NombreCategoria"].ToString(),
                        Precio = Convert.ToDecimal(dr["Precio"]),
                        Stock = Convert.ToInt32(dr["Stock"]),
                        FechaRegistro = Convert.ToDateTime(dr["FechaRegistro"])
                    };
                    temporal.Add(producto); // Agregar el producto a la lista temporal
                }
                cn.Close();
            }
            return temporal;
        }

        // Método para filtrar productos por categoría utilizando el stored procedure
        public IEnumerable<Producto> FiltrarProductosPorCategoria(int idCategoria)
        {
            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");
            List<Producto> productosFiltrados = new List<Producto>();
            string connectionString = _iconfig.GetConnectionString("cadena");
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                cn.Open();
                string query = "SpFiltradoProdCate";
                SqlCommand cmd = new SqlCommand(query, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@nombreProducto", DBNull.Value); // No se filtra por nombre de producto
                cmd.Parameters.AddWithValue("@idCategoria", idCategoria);
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Producto producto = new Producto()
                    {
                        IdProducto = Convert.ToInt32(dr["IdProducto"]),
                        Nombre = dr["NombreProducto"].ToString(),
                        NombreCategoria = dr["NombreCategoria"].ToString(),
                        Precio = Convert.ToDecimal(dr["Precio"]),
                        Stock = Convert.ToInt32(dr["Stock"]),
                        FechaRegistro = Convert.ToDateTime(dr["FechaRegistro"])
                    };
                    productosFiltrados.Add(producto);
                }
                cn.Close();
            }
            
            return productosFiltrados;
        }

        // GET
        public IActionResult FiltrarPorCategoria(int idCategoria)
        {

            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");
            ViewData["CantidadProdCr"] = RecoverCantidadProd();

            string nombreCategoria = ObtenerNombreCategoria(idCategoria);
            ViewBag.NombreCategoria = nombreCategoria;

            // Si no encuentra el nombre, es porque no existe
            // En ese caso redirigir a Portal, para mostrar todo
            if (string.IsNullOrEmpty(nombreCategoria))
            {
                return RedirectToAction("Portal");
            }


            // Filtrar productos por categoría
            IEnumerable<Producto> productosFiltrados = FiltrarProductosPorCategoria(idCategoria);
            ViewBag.CategoriaID = idCategoria + ""; // Cadena vacia para manejar como string

            // Obtener cantidad de resultador
            int cantidadProductosFiltrados = productosFiltrados.Count();

            // Almacenar la cantidad de productos por categoria obtenidos
            ViewBag.CantidadPorCategoria = cantidadProductosFiltrados;

            return View("Portal", productosFiltrados); // Mostrar los productos filtrados en la misma vista del portal
        }


        // Método para obtener el nombre de la categoría
        private string ObtenerNombreCategoria(int idCategoria)
        {
            string nombreCategoria = "";
            string connectionString = _iconfig.GetConnectionString("cadena");
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                cn.Open();
                string query = "SELECT NombreCategoria FROM Categoria WHERE IdCategoria = @idCategoria";
                SqlCommand cmd = new SqlCommand(query, cn);
                cmd.Parameters.AddWithValue("@idCategoria", idCategoria);
                object result = cmd.ExecuteScalar();
                if (result != null)
                {
                    nombreCategoria = result.ToString();
                }
                cn.Close();
            }
            return nombreCategoria;
        }


        public IActionResult Portal()
        {

            //espacio para definir el Session canasta, no no existe definir
            if (HttpContext.Session.GetString("canasta") == null)
            {
                HttpContext.Session.SetString("canasta",
                JsonConvert.SerializeObject(new List<Producto>()));
            }
            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");
            ViewData["CantidadProdCr"] = RecoverCantidadProd();
            
            //enviar el catalogo a la vista
            return View(Catalogo());
        }

        // Método para buscar productos por nombre utilizando el stored procedure
        public IActionResult BuscarProductoPorNombre(string nombreProducto)
        {
            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");
            ViewData["CantidadProdCr"] = RecoverCantidadProd();

            // Filtrar productos por nombre
            IEnumerable<Producto> productosFiltrados = FiltroBusquedaProd(nombreProducto);

            int cantidadProductosFiltrados = productosFiltrados.Count();
            ViewBag.CantidadCoincidencias = cantidadProductosFiltrados;


            if (string.IsNullOrEmpty(nombreProducto))
            {
                return RedirectToAction("Portal");
            }

            ViewBag.Busqueda = nombreProducto;

            return View("Portal", productosFiltrados); // Mostrar los productos filtrados en la misma vista del portal
        }

        // Método para buscar productos por nombre utilizando el stored procedure
        public IEnumerable<Producto> FiltroBusquedaProd(string nombreProducto)
        {
            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");
            List<Producto> productosFiltrados = new List<Producto>();

            // MANEJO DE NULOS , PROD = 0 && 1 , TRUE
            if (!string.IsNullOrEmpty(nombreProducto))
            {
                string connectionString = _iconfig.GetConnectionString("cadena");
                using (SqlConnection cn = new SqlConnection(connectionString))
                {
                    cn.Open();
                    string query = "SpBuscarProductoPorNombre";
                    SqlCommand cmd = new SqlCommand(query, cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@nombreProducto", nombreProducto);
                    SqlDataReader dr = cmd.ExecuteReader();
                    while (dr.Read())
                    {
                        Producto producto = new Producto()
                        {
                            IdProducto = Convert.ToInt32(dr["IdProducto"]),
                            Nombre = dr["NombreProducto"].ToString(),
                            NombreCategoria = dr["NombreCategoria"].ToString(),
                            Precio = Convert.ToDecimal(dr["Precio"]),
                            Stock = Convert.ToInt32(dr["Stock"]),
                            FechaRegistro = Convert.ToDateTime(dr["FechaRegistro"])
                        };
                        productosFiltrados.Add(producto);
                    }
                    cn.Close();
                }
            }
 
            return productosFiltrados;
        }


        public IActionResult Seleccionar(int id = 0)
        {
            ViewData["IdUsuario"] = HttpContext.Session.GetString("IdUsuario");
            ViewData["FullName"] = HttpContext.Session.GetString("FullName");

Views/ECommerce/Comprar.cshtml
@model Ecommerce_2024_1_NJD.Models.UsuarioRegPedido

@{
    Layout = "_LayoutTienda";
}

@{
    ViewData["Title"] = "Realizar Pedido";
}

<style>
    body {
        background-color: #EEEEEE;
    }
</style>

<!--

<h1>Comprar</h1>
<p>
    <a asp-action="Portal" class="btn btn-primary">Ir a la Tienda</a>
</p>
<a asp-action="Logout" asp-controller="Usuario">Cerrar Sesion</a>

-->

@if (!string.IsNullOrEmpty(ViewData["IdUsuario"]?.ToString()) && !string.IsNullOrEmpty(ViewData["FullName"]?.ToString()))
{

    <div class="mx-auto rounded-2 mt-5 p-3 bg-white" style="width: 600px; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">

        <div class="w-90 mx-auto">
            <h3 class="fw-bold">¡Ya casi terminas de hacer tu pedido!</h3>
            <hr class="my-2">
            <form method="post" asp-action="Comprar">
                <div class="form-group my-4">
                    <label class="fw-bold" for="dniC">Ingresa el número de tu DNI</label>
                    <input type="text" class="form-control" id="dni" name="dni">
                </div>
                <div class="form-group my-4">
                    <label class="fw-bold" for="direccionDestino">Indica la dirección de entrega</label>
                    <input type="text" class="form-control" id="direccionDestino" name="direccionDestino">
                </div>

                <hr class="my-2">

                <!--Luego renombrar y redirigir para continuar al pago-->
                <center>
                    <button type="submit" class="btn btn-dark rounded-5 px-4 py-2">Realizar Pedido</button>
                </center>
            </form>
        </div>

    </div>
}
else
{
    <div class="alert alert-danger" role="alert">
        No deberías estar viendo esto
    </div>
}




<!--
<form method="post" asp-action="Comprar">
    <div class="form-group">
        <label for="dniC">DNI:</label>
        <input type="text" class="form-control" id="dni" name="dni">
    </div>
    <div class="form-group">
        <label for="direccionDestino">Dirección de Destino:</label>
        <input type="text" class="form-control" id="direccionDestino" name="direccionDestino">
    </div>
    <button type="submit" class="btn btn-primary">Comprar</button>
</form>
<div>
    @ViewBag.mensaje
</div>-->

Views/ECommerce/Portal.cshtml
@model IEnumerable<Producto>

@{
    Layout = "_LayoutTienda";
}

@{
    ViewData["Title"] = "Catálogo de Productos";
}

@{
    //Habilitar footer
    ViewData["Footer"] = "Si";
}

<style>
    
    .catalogo{
        max-width: 1000px;
        width: 90%;
        margin: 0 auto;
        padding: 0 auto;
    }

    .row-cols-3>*{
        width: 22%;
        font-family: 'Helvetica', sans-serif;
    }

    
    @@media (max-width: 1200px) {

        .row-cols-3>*{
            width: 30%;
        }
    }

    @@media (max-width: 850px) {

        .row-cols-3>*{
            width: 40%;
        }
    }

    @@media (max-width: 600px) {

        .row-cols-3>*{
            width: 80%;
        }
    }

    .btn-agregar{
        background-color: black;
        color: white;
        width: 100%;
        font-weight: bold;
        border-radius:3px;
    }

    .btn-agregar:hover {
        background-color: #CFCFCF;
        color: black;
    }

    .product{
        background-color: rgb(255, 255, 255);
        border-radius: 2px;
        transform: scale(1.0, 1.0);
        transition: all 250ms;
        box-shadow: 0 1px 2px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.07), 0 4px 8px rgba(0,0,0,0.07), 0 8px 16px rgba(0,0,0,0.07), 0 16px 32px rgba(0,0,0,0.07), 0 32px 64px rgba(0,0,0,0.07);
    }

    .product:hover{
        transform: scale(1.05, 1.05);
        transition: all 500ms;
    }

    body{
        display: grid;
        min-height: 100vh;
        grid-template-rows: auto 1fr auto
    }

</style>


<div style="max-width: 1000px;width: 90%;" class="mx-auto mt-3">
    @if (!string.IsNullOrEmpty(ViewBag.Busqueda))
    {
        // Si haces una busqueda mediante la barra
        <h3>Resultados para <span class="fw-bold">"@ViewBag.Busqueda"</span></h3>
        <p>Se han encontrado @ViewBag.CantidadCoincidencias resultados</p>
        <hr class="w-100 mb-0">
    }
    else if (!string.IsNullOrEmpty(ViewBag.NombreCategoria))
    {
        // Si seleccionas una categoría
        <h3>Artículos de <span class="fw-bold">"@ViewBag.NombreCategoria"</span></h3>
        <p>Mostrando @ViewBag.CantidadPorCategoria resultados</p>
        <hr class="w-100 mb-0">
    }
    else
    {
        <h3>Nuestros artículos</h3>
        <p>Todos los productos disponibles</p>
        <hr class="w-100 mb-0">
    }
</div>

@if (Model.Count() > 0)
{
    <div class="catalogo">

        <div class="row row-cols-3 justify-content-around">
            @foreach (var producto in Model)
            {
                <div class="product col my-4 align-center text-center py-3">

                    <div class="prod-img px-2 ratio ratio-1x1">
                        <img class="p-1 bg-white rounded" src="@Url.Action("ObtenerImagen", "Producto", new { id = producto.IdProducto })" alt="imagen del producto" width="100%">
                    </div>
                    <hr class="w-100 my-2 text-white">
                    <div class="prod-info px-2">
                        <p title="@producto.Nombre" class="my-1 fs-5 fw-bold" style="max-width: 100%; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; text-transform: uppercase">@Html.DisplayFor(modelItem => producto.Nombre)</p>
                        <p class="my-2 d-none">@Html.DisplayFor(modelItem => producto.NombreCategoria)</p>
                        <p class="my-1 fw-bold">S/.&nbsp;@Html.DisplayFor(modelItem => producto.Precio)</p>

                    </div>
                    <hr class="w-100 my-2 text-white">
                    @if (!string.IsNullOrEmpty(ViewData["IdUsuario"]?.ToString()) && !string.IsNullOrEmpty(ViewData["FullName"]?.ToString()))
                    {
                        @Html.ActionLink("Agregar al carrito", "Seleccionar", new { id = producto.IdProducto }, new { @class = "btn btn-agregar" })
                    }
                    else
                    {
                        <a class="btn-agregar btn" href="@Url.Action("LoginPage", "Usuario")">Agregar al carrito</a>
                    }

                </div>
            }
        </div>
    </div>
}
else
{
    <div class="mx-auto rounded-2 p-3 my-5 bg-white" style="max-width: 500px; width: 90%;box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 10px;">
        <div class="d-flex w-90 mx-auto text-center justify-content-center">
            <div class="d-flex flex-wrap align-items-center w-30">
                <img class="align-middle" style="width: 100px;" src="https://cdn-icons-png.flaticon.com/512/1178/1178479.png" alt="Carrito">
            </div>

            <div class="w-50">
                <p class="fw-bold fs-3 m-0">Lo sentimos</p>
                <p>No se encontraron resultados.</p>
            </div>

        </div>

        <hr class="my-2">

        <div class="w-100 text-center">
            <a class="btn btn-dark fw-bold w-60 py-2" style="border-radius: 50px;" asp-action="Portal" asp-controller="ECommerce">
                Ver productos
            </a>
        </div>
    </div>
}

Views/ECommerce/Resumen.cshtml
@model IEnumerable<Ecommerce_2024_1_NJD.Models.Producto>

@{
    Layout = "_LayoutTienda";
}

@{
    ViewData["Title"] = "Carrito";
}

@{
    //Habilitar footer
    ViewData["Footer"] = "Si";
}


<div class="w-100">

    <style>
        body {
            background-color: #EEEEEE;
        }
    </style>

    @if (Model.Any())
    {


    <div class="mx-auto " style="width: 1000px;">

        <div class="px-2 py-3">
            <a asp-action="Portal" class="btn btn-dark fw-bold">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8" />
                </svg>&nbsp;Seguir comprando
            </a>
        </div>

        <!--Tener cuidado con estos dos-->

        <hr class="my-2">

        <div class="mx-auto px-3 py-2 bg-dark rounded-3" style="width: calc(100% - 1rem);box-shadow: rgba(0, 0, 0, 0.24) 0px 0px 0px">
            <p style="text-transform:uppercase;" class="mb-0 fw-bold fs-3 text-light text-center rounded-4">Tu carro de la compra</p>
        </div>


        <!--DIV PRODUCTOS-->
        <div class="d-flex">
            <div class="col-8 py-3 px-2">

                @foreach (var item in Model)
                {
                    <!--Producto-->
                    <div style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;" class="bg-white rounded-4 d-flex p-3 mt-0 mb-4">
                        <div class="w-35">
                            <img class="p-2 bg-dark rounded" style="width: 200px; height: 200px;" src="@Url.Action("ObtenerImagen", "Producto", new { id = item.IdProducto })" alt="Imagen del Producto" />
                        </div>

                        <div class="w-65">
                            <p style="word-wrap:break-word" class="fw-bold fs-4 my-0">
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </p>
                            <hr class="my-2">

                            @{
                                decimal total = item.Precio * item.cantidad;
                            }

                            <p style="word-wrap:break-word" class="my-3">
                                @Html.DisplayFor(modelItem => item.cantidad)&nbsp;unidades&nbsp;x&nbsp;S/&nbsp;@Html.DisplayFor(modelItem => item.Precio)
                            </p>
                            <p style="word-wrap:break-word" class="text-end fw-bold fs-4">
                                S/&nbsp;@total
                            </p>
                            <hr class="my-2">
                            <div class="d-flex justify-content-end">
                                <!-- POR SI QUIERO AGREGAR MAS BOTONES
                                <a class="d-block text-dark" href="">Btnrandom</a>
                                &nbsp;|&nbsp;
                                -->
                                @Html.ActionLink("Eliminar", "Delete", new { id = item.IdProducto, q = item.cantidad }, new { @class = "d-block text-dark" })
                            </div>
                        </div>
                    </div>
                }

            </div>

            <!--DIV TOTAL-->
            <div class="col-4 py-3 px-2">
                <div style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;" class="bg-white rounded p-3">
                    <div class="">
                        <p class="fw-bold fs-5 my-0">Total estimado</p>
                        <hr class="my-2">
                        <p style="word-wrap:break-word" class="text-end fw-bold fs-4">
                            S/&nbsp;@Model.Sum(c => c.monto)
                        </p>

                        <div class="text-center">
                            <a asp-action="Comprar" style="border-radius: 4px;" class="fw-bold btn btn-dark w-100">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket" viewBox="0 0 16 16">
                                    <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9zM1 7v1h14V7zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5" />
                                </svg>
                                &nbsp;
                                Continuar compra
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>




    </div>
    }
    else
    {
        <div class="mx-auto rounded-2 p-3 mt-4 mb-4 bg-white" style="width: 520px; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
            <div class="d-flex w-90 mx-auto text-center justify-content-center">
                <div class="d-flex flex-wrap align-items-center w-30">
                    <img class="align-middle" style="width: 100px;" src="https://upload.wikimedia.org/wikipedia/commons/f/f2/Shopping-cart-transparent-icon.png" alt="Carrito">
                </div>

                <div class="w-50">
                    <p class="fw-bold fs-3 m-0">Carrito vacío</p>
                    <p>Aprovecha los precios especiales que tenemos para ti.</p>
                </div>

            </div>

            <hr class="my-2">

            <div class="w-100 text-center">
                <a asp-action="Portal" class="btn btn-dark fw-bold w-60 py-2" style="border-radius: 50px;">
                    Ver productos
                </a>
            </div>
        </div>
    }

</div>

Views/ECommerce/Seleccionar.cshtml
@model Ecommerce_2024_1_NJD.Models.Producto

@{
    Layout = "_LayoutTienda";
}


@{
    ViewData["Title"] = "Detalles de producto";
}

@{
    //Habilitar footer
    ViewData["Footer"] = "Si";
}


<style>
    *:focus {
        outline: none;
    }

    body {
        background-color: #EEEEEE;
    }

    .input-cantidad{
        text-align: center;
        font-size: 14pt;
        height: 100%;
        border: 0;
        width: 40px;
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    }

    /* Chrome, Safari, Edge, Opera */
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    /* Firefox */
    input[type=number] {
        -moz-appearance: textfield;
    }

</style>

<div class="w-100 mx-auto" style="background-color: #EEEEEE; margin:30px auto;">
    <div class="bg-white mx-auto" style="max-width: 1000px; width:95%;box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 10px;">
        <div class="col-12 bg-white px-3 py-2">
            <a asp-action="Portal" class="btn btn-dark fw-bold">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8" />
                </svg>&nbsp;Regresar a portal
            </a>
        </div>
        <hr class="my-0">
        <div class="w-100 bg-white mx-auto d-flex py-3 ">
            <div class="col-5 text-center bg-white">
                <img class="rounded" style="width: 320px; height: 320px;" src="@Url.Action("ObtenerImagen", "Producto", new { id = Model.IdProducto })" alt="Imagen del Producto" />
            </div>
            <div class="col-7 bg-white px-2 py-4">
                <div class="d-flex w-95 mx-auto">
                    <p class="bg-white fw-bold my-0 col-10">@Html.DisplayFor(model => model.NombreCategoria)</p>
                    <p class="bg-white my-0 col-2 align-bottom" style="font-size: 12px">Código:&nbsp;@Html.DisplayFor(model => model.IdProducto)</p>
                </div>

                <p class="w-95 mx-auto bg-white my-1 fs-4">@Html.DisplayFor(model => model.Nombre)</p>

                <hr>

                <div class="w-95 mx-auto d-flex">

                    <div class="col-12 bg-white mx-auto">
                        <p class="fw-bold fs-3 bg-white m-0">S/&nbsp;@Html.DisplayFor(model => model.Precio)</p>
                        
                        <form action="Seleccionar" method="post">
                            <div class="d-flex my-3 justify-content-center">
                                <button style="border-radius: 0;" class="btn btn-dark" id="btnRestar">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-lg" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11A.5.5 0 0 1 2 8" />
                                    </svg>
                                </button>
                                &nbsp;
                                <div>
                                    @Html.TextBox("cantidad", 1, new { type = "number", min = 1, max = Model.Stock, @class = "input-cantidad" })
                                </div>
                                &nbsp;
                                <button style="border-radius: 0;" class="btn btn-dark" id="btnSumar">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2" />
                                    </svg>
                                </button>
                            </div>

                            <center>
                                <div>
                                        @Html.Hidden("idProducto", Model.IdProducto)
                                        <div class="row">
                                            <div class="col-md-12">
                                                <input style="border-radius: 250px;" class="btn btn-dark mx-auto w-60 py-3" type="submit" value="Agregar al carrito"/>
                                            </div>
                                        </div>
                                </div>

                            </center>
                        </form>
                    </div>
                </div>

            </div>
        </div>


    </div>
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Obtener elementos
        var btnSumar = document.getElementById("btnSumar");
        var btnRestar = document.getElementById("btnRestar");
        var inputCantidad = document.querySelector(".input-cantidad");

        // Agregar evento al botón Sumar
        btnSumar.addEventListener("click", function (event) {
            event.preventDefault(); // Evitar el comportamiento predeterminado del botón
            // Obtener el valor actual del input
            var valorActual = parseInt(inputCantidad.value);
            // Incrementar el valor
            inputCantidad.value = valorActual + 1;
        });

        // Agregar evento al botón Restar
        btnRestar.addEventListener("click", function (event) {
            event.preventDefault(); // Evitar el comportamiento predeterminado del botón
            // Obtener el valor actual del input
            var valorActual = parseInt(inputCantidad.value);
            // Verificar que el valor sea mayor que el mínimo
            if (valorActual > 1) {
                // Disminuir el valor
                inputCantidad.value = valorActual - 1;
            }
        });
    });
</script>

<!--
<div>
    @ViewBag.mensaje
</div>
-->